export { Header } from './header'
export { Hero } from './hero'
export { Stats } from './stats'
export { Features } from './features'
export { HowItWorks } from './how-it-works'
export { Testimonials } from './testimonials'
export { CTA } from './cta'
export { Footer } from './footer'
